#!/bin/bash 
# bash script for running a clean install for those that just want get it done and run.
# tested on Linuxmint 19.1
# Suggest creating a build folder ie. HantekSetup in your home folder. 
# run command 'bash installopenhantek'
#
# grabbing a copy of the original install, for interest sake and comparrision for those interested.
# cloned to -org as we need the openhantek folder for the latest version to compile correctly.
# not necessary and can be commented out.
#
git clone https://github.com/openhantek/openhantek openhantek-org
#
# cloning to the openhantek folder as the typical git copy to openhantek6022 folder crashes when you attempt to build it.
git clone https://github.com/openhantek/openhantek6022 openhantek
#
# install associated dependancies
apt install g++ make cmake qttools5-dev qttools5-dev-tools libfftw3-dev binutils-dev libusb-1.0-0-dev libqt5opengl5-dev mesa-common-dev libgl1-mesa-dev libgles2-mesa-dev
echo "installed dependancies"
#
# building openhantek
#
cd openhantek
echo "Create build directory"
mkdir build
echo "Move into build Directory"
cd build
echo "Moved into build directory"
echo "About to cmake"
cmake ../
echo "cmake finished"
echo "About to make -j2"
make -j2
echo "make -j2 complete and we should be done compiling!"
echo "Installing compiled app"
sudo make install
echo "Done, run OpenHantek to run scope software"
echo "First run on power up needs to upload firmware, this happens but doesn't come back to you. Give it a few seconds click close, and run the software again.
echo "to run the openhantek software from lowercase, run sudo ln -s /usr/local/bin/OpenHantek /usr/local/bin/openhantek
